# -*- coding: utf-8 -*-
"""Design number matching streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10t-wWfCK5q65-Rp-EAdjPCPkoxQjIPbo
"""

import pandas as pd
import re
import streamlit as st # Assuming you'll use Streamlit

# Function to find the citable reference for a given design number
def find_citable_reference(design_number, df):
    references = []
    for _, row in df.iterrows():
        description = str(row['Description'])
        match = re.search(r'Designs (\d+)-(\d+)', description)
        if match:
            start, end = int(match.group(1)), int(match.group(2))
            if start <= design_number <= end:
                references.append(row['Citable Reference'])
    if references:
        return references
    else:
        return ["Design number not found in any range."]

# Function to find the relevant rows for a given design number
def find_relevant_rows(design_number, df):
    relevant_rows = []
    for index, row in df.iterrows():
        description = str(row['Description'])
        match = re.search(r'Designs (\d+)-(\d+)', description)
        if match:
            start, end = int(match.group(1)), int(match.group(2))
            if start <= design_number <= end:
                relevant_rows.append(row)
    if relevant_rows:
        return pd.DataFrame(relevant_rows)
    else:
        return pd.DataFrame()

# --- Streamlit App ---

st.title('Design Number Lookup')

# File upload for the CSV
uploaded_file = st.file_uploader("Upload your CSV file", type="csv")

df = None
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.success("File uploaded successfully!")

    # Input for design number
    design_number_input = st.text_input('Enter Design Number', '')

    if design_number_input:
        try:
            design_number = int(design_number_input)
            relevant_df = find_relevant_rows(design_number, df)

            if not relevant_df.empty:
                st.write(f"Results for Design Number {design_number}:")
                # Select and display the desired columns
                display_cols = ['Citable Reference', 'Context Description', 'Title', 'Covering Dates']
                st.dataframe(relevant_df[display_cols]) # Use st.dataframe for displaying tables
            else:
                st.warning(f"Design number {design_number} not found in any range.")
        except ValueError:
            st.error("Please enter a valid integer for the design number.")
else:
    st.info("Please upload a CSV file to get started.")